[build-system]
requires = ["hatchling>=1.5.0", "hatch-nodejs-version>=0.3.2", "jupyter-builder>=1.2.0,<2"]
build-backend = "hatchling.build"

[project]
name = "jupyterlite-pdf-exporter"
readme = "README.md"
license = "GPL-2.0-or-later"
license-files = ["LICENSE.txt", "LICENSE-PANDOC.txt", "LICENSE-TYPST.txt"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "Intended Audience :: Developers",
    "Environment :: Web Environment",
    "Environment :: WebAssembly",
    "Environment :: Plugins",
    "Programming Language :: JavaScript",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Text Processing :: Markup",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
authors = [
    { name = "Agriya Khetarpal" },
]
dependencies = [
]
dynamic = ["version", "description", "urls", "keywords"]

[dependency-groups]
dev = [
    "jupyterlab>=4",
    "jupyter-builder>=1.2.0,<2",
]

[tool.hatch.version]
source = "nodejs"

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls", "keywords"]

[tool.hatch.build.targets.sdist]
artifacts = ["jupyterlite_pdf_exporter/labextension"]
exclude = [".github", "binder", "venv", "node_modules"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyterlite_pdf_exporter/labextension" = "share/jupyter/labextensions/jupyterlite-pdf-exporter"
"install.json" = "share/jupyter/labextensions/jupyterlite-pdf-exporter/install.json"

[tool.hatch.build.hooks.version]
path = "jupyterlite_pdf_exporter/_version.py"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "jupyterlite_pdf_exporter/labextension/static/style.js",
    "jupyterlite_pdf_exporter/labextension/package.json",
]
skip-if-exists = ["jupyterlite_pdf_exporter/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "jupyterlite_pdf_exporter/labextension"

[tool.check-wheel-contents]
ignore = ["W002"]
