name: Update Playwright Snapshots

on:
  issue_comment:
    types: [created, edited]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

# Keep in sync with the integration-tests job in build.yml
env:
  MAXIMUM_JUPYTERLAB_VERSION: jupyterlab>=4.6.0,<5

jobs:
  update-snapshots:
    name: Update snapshots
    if: >
      (
        github.event.issue.author_association == 'OWNER' ||
        github.event.issue.author_association == 'COLLABORATOR' ||
        github.event.issue.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.comment.author_association == 'MEMBER'
      ) && github.event.issue.pull_request && contains(github.event.comment.body, 'please update snapshots')
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push the branch with updated snapshots
      pull-requests: write # to react to the triggering comment
    steps:
      - name: React to the triggering comment
        run: |
          gh api repos/$GITHUB_REPOSITORY/issues/comments/$GITHUB_EVENT_COMMENT_ID/reactions --raw-field 'content=+1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_COMMENT_ID: ${{ github.event.comment.id }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Info
        id: pr
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMENT_AT: ${{ github.event.comment.created_at }}
        run: |
          pr="$(gh api /repos/${GH_REPO}/pulls/${PR_NUMBER})"
          head_sha="$(echo "$pr" | jq -r .head.sha)"
          pushed_at="$(echo "$pr" | jq -r .pushed_at)"

          if [[ $(date -d "$pushed_at" +%s) -gt $(date -d "$COMMENT_AT" +%s) ]]; then
              echo "Updating is not allowed because the PR was pushed to (at $pushed_at) after the triggering comment was issued (at $COMMENT_AT)"
              exit 1
          fi

          echo "head_sha=$head_sha" >> $GITHUB_OUTPUT

      - name: Checkout the branch from the PR that triggered the job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: gh pr checkout $GITHUB_EVENT_ISSUE_NUMBER

      - name: Validate the fetched branch HEAD revision
        env:
          EXPECTED_SHA: ${{ steps.pr.outputs.head_sha }}
        run: |
          actual_sha="$(git rev-parse HEAD)"

          if [[ "$actual_sha" != "$EXPECTED_SHA" ]]; then
              echo "The HEAD of the checked out branch ($actual_sha) differs from the HEAD commit available at the time when trigger comment was submitted ($EXPECTED_SHA)"
              exit 1
          fi

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@94b14ddfbdd1ed651e9f9343ae2409ab5c73a6a8 # v1

      - name: Build and install the extension
        run: |
          set -eux
          python -m pip install build "${MAXIMUM_JUPYTERLAB_VERSION}"
          jlpm
          python -m build --wheel
          python -m pip install dist/jupyterlite_pdf_exporter*.whl

          jupyter labextension list 2>&1 | grep -ie "jupyterlite-pdf-exporter.*OK"

      - name: Update the snapshots and push them
        uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@94b14ddfbdd1ed651e9f9343ae2409ab5c73a6a8 # v1
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Playwright knows how to start JupyterLab server
          start_server_script: 'null'
          test_folder: ui-tests
          npm_client: jlpm
